### ISSUE TITLE
library doesn't log X-Correlation-ID values at log level fine()

### ISSUE THREAD

**Issue by kenmccracken** [heremaps/here-aaa-java-sdk#60]
As a developer, I want to see the X-Correlation-ID logged when I configure my logging to include fine("messages").
Currently, the X-Correlation-ID header is not loggable with the response, unless I inject my own HTTP Provider.

Acceptance criteria:

The X-Correlation-ID is logged via something like 
```
LOGGER.fine("X-Correlation-ID: {}", xCorrelationId);
```
Note that the headers are not currently exposed in the HttpResponse, so you'll need to add that as well.

**Comment by stwwalton** [comment]
X-Correlation-ID is logged as it is added to the request header.

**Comment by kenmccracken** [comment]
Released in the latest version 0.4.18.
See also PR #67
