### ISSUE TITLE
library should make correlationId available in AccessTokenResponse.

### ISSUE THREAD

**Issue by kenmccracken** [heremaps/here-aaa-java-sdk#65]
From the OLP specs, X-Correlation-ID is returned to customer in response headers.
It is best if we make this value available to customers on the AccessTokenResponse object.  
Suggested to follow a similar pattern to https://github.com/heremaps/here-aaa-java-sdk/pull/63, but on the response side, to use a private transient String correlationId with setter/getter.

**Comment by stwwalton** [comment]
Done

**Comment by kenmccracken** [comment]
Included in latest release 0.4.18.
Which includes PR #67
